export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_SPINNER_OPEN = 'FETCH_PRODUCTS_SPINNER_OPEN';
export const FETCH_PRODUCTS_SPINNER_CLOSE = 'FETCH_PRODUCTS_SPINNER_CLOSE';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_SELECTED_PRODUCT_SUCCESS = 'FETCH_SELECTED_PRODUCT_SUCCESS';
export const FETCH_SELECTED_PRODUCT_REQUEST = 'FETCH_SELECTED_PRODUCT_REQUEST';
export const FETCH_SELECTED_PRODUCT_FAILURE = 'FETCH_SELECTED_PRODUCT_FAILURE';
export const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';

export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_SPINNER_OPEN = 'FETCH_PROPERTIES_SPINNER_OPEN';
export const FETCH_PROPERTIES_SPINNER_CLOSE = 'FETCH_PROPERTIES_SPINNER_CLOSE';
export const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE';

export const NOTIFICATION_CREATED_PRODUCT = 'NOTIFICATION_CREATED_PRODUCT';
export const NOTIFICATION_EDITED_PRODUCT = 'NOTIFICATION_EDITED_PRODUCT';
export const NOTIFICATION_DELETED_PRODUCT = 'NOTIFICATION_DELETED_PRODUCT';
export const NOTIFICATION_CREATED_PROPERTY = 'NOTIFICATION_CREATED_PROPERTY';
export const NOTIFICATION_DELETED_PROPERTY = 'NOTIFICATION_DELETED_PROPERTY';
export const NOTIFICATION_GO_TO_CLOSE = 'NOTIFICATION_GO_TO_CLOSE';
export const NOTIFICATION_STATUS_RESET = 'NOTIFICATION_STATUS_RESET';

export const USER_IS_LOGGED_IN = 'USER_IS_LOGGED_IN';
export const USER_IS_LOGGED_OUT = 'USER_IS_LOGGED_OUT';
export const USER_IS_LOGGED_REQUEST = 'USER_IS_LOGGED_REQUEST';