const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

const FETCH_SELECTED_PRODUCT_SUCCESS = 'FETCH_SELECTED_PRODUCT_SUCCESS';
const FETCH_SELECTED_PRODUCT_REQUEST = 'FETCH_SELECTED_PRODUCT_REQUEST';
const FETCH_SELECTED_PRODUCT_FAILURE = 'FETCH_SELECTED_PRODUCT_FAILURE';

const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
const FETCH_PROPERTIES_REQUEST = 'FETCH_PROPERTIES_REQUEST';
const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE';

export {
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_REQUEST,
    FETCH_PRODUCTS_FAILURE,
    FETCH_SELECTED_PRODUCT_SUCCESS,
    FETCH_SELECTED_PRODUCT_REQUEST,
    FETCH_SELECTED_PRODUCT_FAILURE,
    FETCH_PROPERTIES_SUCCESS,
    FETCH_PROPERTIES_REQUEST,
    FETCH_PROPERTIES_FAILURE,
}