const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
const PRODUCTS_REQUESTED = 'PRODUCTS_REQUESTED';

const PROPERTIES_LOADED = 'PROPERTIES_LOADED';

export {
    PRODUCTS_LOADED,
    PROPERTIES_LOADED,
    PRODUCTS_REQUESTED
}