const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_SPINNER_OPEN = 'FETCH_PRODUCTS_SPINNER_OPEN';
const FETCH_PRODUCTS_SPINNER_CLOSE = 'FETCH_PRODUCTS_SPINNER_CLOSE';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

const FETCH_SELECTED_PRODUCT_SUCCESS = 'FETCH_SELECTED_PRODUCT_SUCCESS';
const FETCH_SELECTED_PRODUCT_REQUEST = 'FETCH_SELECTED_PRODUCT_REQUEST';
const FETCH_SELECTED_PRODUCT_FAILURE = 'FETCH_SELECTED_PRODUCT_FAILURE';
const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';

const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
const FETCH_PROPERTIES_SPINNER_OPEN = 'FETCH_PROPERTIES_SPINNER_OPEN';
const FETCH_PROPERTIES_SPINNER_CLOSE = 'FETCH_PROPERTIES_SPINNER_CLOSE';
const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE';

const NOTIFICATION_CREATED_PRODUCT = 'NOTIFICATION_CREATED_PRODUCT'
const NOTIFICATION_EDITED_PRODUCT = 'NOTIFICATION_EDITED_PRODUCT';
const NOTIFICATION_DELETED_PRODUCT = 'NOTIFICATION_DELETED_PRODUCT';
const NOTIFICATION_CREATED_PROPERTY = 'NOTIFICATION_CREATED_PROPERTY';
const NOTIFICATION_DELETED_PROPERTY = 'NOTIFICATION_DELETED_PROPERTY';
const NOTIFICATION_GO_TO_CLOSE = 'NOTIFICATION_GO_TO_CLOSE';
const NOTIFICATION_STATUS_RESET = 'NOTIFICATION_STATUS_RESET';

const USER_IS_LOGGED_IN = 'USER_IS_LOGGED_IN';
const USER_IS_LOGGED_OUT = 'USER_IS_LOGGED_OUT';

export {
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_SPINNER_OPEN,
    FETCH_PRODUCTS_SPINNER_CLOSE,
    FETCH_PRODUCTS_FAILURE,
    FETCH_SELECTED_PRODUCT_SUCCESS,
    FETCH_SELECTED_PRODUCT_REQUEST,
    FETCH_SELECTED_PRODUCT_FAILURE,
    CLEAR_SELECTED_PRODUCT,
    FETCH_PROPERTIES_SUCCESS,
    FETCH_PROPERTIES_SPINNER_OPEN,
    FETCH_PROPERTIES_SPINNER_CLOSE,
    FETCH_PROPERTIES_FAILURE,
    NOTIFICATION_CREATED_PRODUCT,
    NOTIFICATION_EDITED_PRODUCT,
    NOTIFICATION_DELETED_PRODUCT,
    NOTIFICATION_CREATED_PROPERTY,
    NOTIFICATION_DELETED_PROPERTY,
    NOTIFICATION_GO_TO_CLOSE,
    USER_IS_LOGGED_IN,
    USER_IS_LOGGED_OUT,
    NOTIFICATION_STATUS_RESET
}